MYSQL:
  # 自定义次数据库链接名称
  name: 'shaw_test'
  # 数据库链接类型
  type: 'mysql'
  # 数据库链接地址
  host: '114.116.77.31'
  post: '3306'
  # 数据库链接用户名
  username: 'root'
  # 数据库链接密码
  password: 'admin8980'
  # 数据库名
  database: 'uniubi-tool'
  # 自定义加载类型
  entities: "mysql"
  # 数据库打印日志
  logging: true
  # 是否开启同步数据表功能
  synchronize: true
  # 重连次数
  retryAttempts: 3
  # 重连时长间隔
  retryDelay: 3000
  # 输出提示
  logNotifications: true
GITLAB:
  # 组织ID
  GROUP_ID: 183

