name: Devtools

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
jobs:
  publish:
    if: github.actor!= 'dependabot[bot]'
    name: Publish graph
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18 ]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Setup Environment (PR)
        if: ${{ github.event_name == 'pull_request' }}
        shell: bash
        run: |
          echo "COMMIT_SHA=${{ github.event.pull_request.head.sha }}" >>\${GITHUB_ENV}
      - name: Setup Environment (Push)
        if: ${{ github.event_name == 'push' }}
        shell: bash
        run: |
          echo "COMMIT_SHA=\${GITHUB_SHA}" >> \${GITHUB_ENV}
      - name: Build
        run: pnpm run build
      - name: Publish
        uses: easingthemes/ssh-deploy@main
        env:
          SOURCE: 'dist/'
          REMOTE_HOST: 114.116.77.31
          REMOTE_USER: root
          SSH_PRIVATE_KEY: 29b70d82-0cf8-45fa-bc5d-81fd6dcba3aa
          DEVTOOLS_API_KEY: 29b70d82-0cf8-45fa-bc5d-81fd6dcba3aa
          TARGET: /home/server
          REMOTE_PORT: 22 -o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedKeyTypes=+ssh-rsa
#      - name: Publish
#        run: PUBLISH_GRAPH=true pnpm run start
#        env:
#          DEVTOOLS_API_KEY: 29b70d82-0cf8-45fa-bc5d-81fd6dcba3aa
#          REPOSITORY_NAME: ${{ github.event.repository.name }}
#          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
#          TARGET_SHA: ${{ github.event.pull_request.base.sha }}
